### ISSUE TITLE
Pet safe detection?

### ISSUE THREAD

**Issue by C0NTi** [paxswill/r-u-still-there#1]
It appears you have made a project to do exactly what I need.

I have not been able to use  this project yet as I am still awaiting delivery of my MLX90640.

I am just reading your documentation ahead of time and have a question/feature request.

> [tracker]
>Any camera pixel over this temperature will count as a human.
>threshold = { fahrenheit = 80 }

I was wondering if there was anyway to have it require a larger number of pixels count as a human
I have two pet cats and their body temp is very similar as a human but their size is a lot smaller, now I know proximity to the camera will also affect how many pixels would be above threshold.
But it could reduce a lot of false positives if you can say a certain amount of pixels need to exceed temp.

I suppose if i wanted to be very accurate I could try going down the ai image processing route, but your solution is so much more elegant and wont kill my little pi.

**Comment by paxswill** [comment]
I will most definitely keep this in mind for the future; the actual occupancy detection is super rudimentary at the moment (literally just counting blobs of pixels over a threshold), but I’ve been planning out a better algorithm and it is next on my task list. Thank you for bringing this up, as I don’t have any pets right now and probably wouldn’t have thought of it.

**Comment by paxswill** [comment]
There's now a [`tracker.minimum_size`](https://github.com/paxswill/r-u-still-there/blob/d9ed62fe3f65004871ff2d387bc66ec495887218/config_example.toml#L137-L141) config option (available in v0.3.0), which should handle this. The new tracker implementation does do some more complex calculations, but it still runs pretty lean (idling at ~6% usage on a BeagleBone Green—a little bit slower than a Raspberry Pi 2— with an MLX90641 at 16FPS).
